baseurl         = "https://ice-energy.github.io/user9"
languageCode    = "en-us"
title           = "User9 Docs n Recs"
author          = "User Nine"
copyright       = "Copyright (c) 2008 - 2018, Ice-Energy; all rights reserved."
canonifyurls    = false
paginate        = 4
theme           = "hugo-bootstrap"

#disqusShortname = "xxxxxx"
#googleAnalytics = "UA-XXXXXXX-1"

[[menu.main]]
    name       = "TAGS"
    pre        = "<i class='fa fa-tags'></i>"
    weight     = -110
    identifier = "tags"
    url        = "/tags/"

[[menu.main]]
    name       = "CATEGORIES"
    pre        = "<i class='fa fa-folder-open'></i>"
    weight     = -100
    identifier = "categories"
    url        = "/categories/"

[[menu.main]]
    name       = "ABOUT"
    pre        = "<i class='fa fa-info-circle'></i>"
    weight     = -90
    identifier = "about-me"
    url        = "/page/about-me"

[[menu.footer]]
    name       = "DISCLAIMER"
    weight     = -110
    identifier = "disclaimer"
    url        = "/page/disclaimer/"

[[menu.footer]]
    name       = "LICENSE"
    weight     = -120
    identifier = "license"
    url        = "/page/license/"

[params.widgets]
  recent_articles = true
  categories      = true
  tags            = true
  tag_cloud       = true

